### ISSUE TITLE
Semester Project: Topics - Gloria

### ISSUE THREAD

**Issue by LucasWashor** [CultureAsData-UIUC/is310-fall-2024-group-6#7]

**Comment by GloriaLiu930** [comment]
For our project on children's literature and texts, a primary topical focus will be understanding the representation of specific themes or cultural phenomena within children's books across time or media. Meanwhile will involve exploring emerging trends, such as the rise of interactive digital books or the impact of modern cultural movements (like inclusivity or climate awareness) on children's literature.


**Defining the scope:**
Emerging Trends: Discover and analyze new themes or trends in children’s literature, such as STEM-focused books, climate change awareness, or books that address social justice issues.

**Approach:**
Literature Review: Start by identifying key works and studies in the field to provide a foundation.
Textual Analysis: Examine specific texts and their content, language, and illustrations to evaluate how themes are communicated.
Media Comparisons: Compare representations across different media formats (traditional books, audiobooks, apps) and assess the impact on children's engagement and understanding.
Interviews/Surveys: If possible, include insights from educators, parents, or children on the impact of these materials.
